### ISSUE TITLE
Save Completed task

### ISSUE THREAD

**Issue by TaurMorchant** [TaurMorchant/NC_project#15]
Открыть Completed таску, ничего не менять, нажать set Changes
ER: окно закрывается, ничего не меняется
AR: эксепшен в логе, окно не закрывается

**Comment by AndreyVic** [comment]
теперь сменить у task со статусом Completed или Canceled можно только название или описание 
![image](https://user-images.githubusercontent.com/33463480/33528857-14fda6b6-d879-11e7-9089-ae4b3542b4bf.png)
