### ISSUE TITLE
Cancel of Completed task

### ISSUE THREAD

**Issue by TaurMorchant** [TaurMorchant/NC_project#17]
Нажать на кнопку Cancel у таски в статусе Completed
ER: либо кнопка вообще не должна быть доступна, либо сообщение о некорректном действии
AR: статус меняется на Canceled

Помните мы рисовали диаграмму жизненного цикла таски? (кстати, где она? Перенесите в репозиторий, в документацию). Все переходы между статусами должны соответствовать этой диаграмме. То есть если между статусами нет стрелочки, значит программа не должна НИКАКИМ образом позволять совершать этот переход.

**Comment by artyomefimov** [comment]
исправил
