### ISSUE TITLE
Set date in past

### ISSUE THREAD

**Issue by TaurMorchant** [TaurMorchant/NC_project#20]
Создать новую таску, ввести время нотификации в прошлом.
ER: отображается сообщение о некорректном вводе, по его закрытию пользователь может продолжать редактирование
ER: отображается сообщение о некорректном вводе, по его закрытию окно редактирования таски так же закрывается

**Comment by AndreyVic** [comment]
теперь окно не закрывается а просто показывается окно об ошибке
