### ISSUE TITLE
Complet and Cancel buttons in Task Form

### ISSUE THREAD

**Issue by TaurMorchant** [TaurMorchant/NC_project#21]
Сейчас в Task Form пользователь может явно сменить статус таски. Пользователь не должен иметь возможность вмешиваться в жизненный цикл напрямую (менять статус произвольно). Пользователь может лишь нажимать на кнопки (совершать Действия). То есть между "пользователь поменял статус на Cancelled" и "пользователь совершил операцию Cancel таски" есть принципиальное различие. Во втором случае можно ввести проверку, а можно ли вообще сейчас совершить это действие, позволяет ли его lifecycle? Плюс операцию Cancel таски - это же не только смена статуса, это может быть еще ряд сопутствующих действия (например, отмена нотификации).
В общем, стоит переделать текущее решение, заменив выпадающий список на кнопки "Complete" и "Cancel"

**Comment by AndreyVic** [comment]
добавлены кнопки. если у задачи статус Completed или Canceled новые кнопки не активны
