### ISSUE TITLE
Notification date after Planned Date

### ISSUE THREAD

**Issue by TaurMorchant** [TaurMorchant/NC_project#22]
Создать таску, задать дату оповещения после даты таски.
ER: показывается сообщение о некорректности ввода
AR: таска создается

Одно дело, когда пользователь переносить нотификашки в будущее (Приложение: "14:00 - пора убраться в комнате", юзер - "Отстань, напомни через час"), а другое - когда он сразу задает "мне надо встретиться с Васей в 5 часов, напомни мне об этом в 6". Немного странный кейс, не находите?

**Comment by AndreyVic** [comment]
Теперь при создании можно только указать за сколько нужно оповестить.  Не возможно создать таску с уже прошедшим временем нотификации и просроченным запланированным временем
