### ISSUE TITLE
Lab2 Requirements

### ISSUE THREAD

**Issue by TaurMorchant** [TaurMorchant/NC_project#33]
Необходимо зафиксировать требования к клиентской и серверной части приложения. Продумать все сценарии.

И верните пожалуйста требования из первой лабы! Они должны быть тоже на виду. К ним прибавятся требования второй лабы.

**Comment by NikitaDestrain** [comment]
[Lab2 Requirements.docx](https://github.com/TaurMorchant/NC_project/files/1587368/Lab2.Requirements.docx)
