### ISSUE TITLE
Config file + parser

### ISSUE THREAD

**Issue by TaurMorchant** [TaurMorchant/NC_project#9]
Реализовать парсер файла конфигураций. На данном этапе в фале должна храниться настройка, содержащая путь до файла с журналом в формате 'ключ=значение'. В дальнейшем могут появиться дополнительные настройки, которые будут влиять на . Парсер должен в момент старта программы считывать все корректные пары 'ключ=значение' из конфигурационного файла и сохранять их в некотором объекте, доступном на уровне всего приложения.

**Comment by AndreyVic** [comment]
Готово
